### ISSUE TITLE
how to deal with jerky mocap data during real robot teleoperation

### ISSUE THREAD

**Issue by idombanker** [yzqin/dex-hand-teleop#12]
[Screencast from 2024年07月28日 23時17分27秒.webm](https://github.com/user-attachments/assets/30d9a2cf-4a68-4769-8c14-a9a06569e2f6)

This is a Record3DSingleHandMotionControl test run using the RealSense API you updated two months ago. During moiton capture, I'm experiencing jerky wrist position data. How did you address this issue?

A few questions and observations:

1. Should we use a low-pass filter to smooth the data, or is a larger model required? If so, is there an existing larger model for hand detection, or is the current one the full-size model?
2. There is a noticeable shift in distance along the axis towards the camera, as shown in the attached video. I haven't delved deeply into it, but it appears to be related to the working range of the RealSense camera. If the hand is placed further than 35 cm from the camera, this issue does not occur. If that really is the case, I suggest implementing a safety soft boundary condition in the code to prevent potential problems.

Any insights or recommendations on how to mitigate these issues would be greatly appreciated.  

Thank you for your attention to this matter.

**Comment by yzqin** [comment]
@idombanker 

1. The low-pass filter is recommended to smooth the data.
2. If you are using Euler angle or similar representation to represent rotation, there can be jerky wrist motion due to its discontinuity. That is why I am using [this Optimizer](https://github.com/yzqin/dex-hand-teleop/blob/3f7b56deed878052ec733a32b503aceee4ca8c8c/hand_teleop/utils/pose_utils.py#L8) instead of a simple rotation matrix to Euler angle conversion function to solve this issue.
3. I believe that there are better AI model for hand pose detection task. I know this one is better than FrankMocap, maybe you can try: https://github.com/yohanshin/WHAM. It is not designed for hand only so I am not sure whether it can meet your requirement.
